_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "IMUL,",
    offsets = "0,",
    addresses = "0x1266,",
    stride_status = "Success",
    stride = 4,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 4,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x1261,",
    stride_status = "Success",
    stride = 1,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 1,
    unroll_factor = 1,
  },
}
