_group = {
  {
    group_size = 3,
    pattern = "SLL",
    opcodes = "VMOVSD,VCVTSD2SS,VCOMISS,",
    offsets = "0,0,12,",
    addresses = "0x13b1,0x13c0,0x13ca,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 8,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x1357,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
}
